### ISSUE TITLE
Allow operator change the state of incidences

### ISSUE THREAD

**Issue by ghost** [Arquisoft/InciDashboard_i3b#13]

**Comment by ghost** [comment]
How is going to be implemented?

> Operators will be able to see information about the incidents they have assigned and control
> them by changing the state and adding comments.

Do we need a login in the dashboard?

**Comment by sergiosantano** [comment]
Yes we need a login in the dashboard

**Comment by sergiosantano** [comment]
Already implemented. We need to show the input field for comments empty
